### ISSUE TITLE
請求書にかかわる動作改善

### ISSUE THREAD

**Issue by kazu0617** [MissMonacoin/monya#12]
請求ボタンで確定を押した後、通貨切り替えを押したタイミングに法定通貨換算ベースにしてほしい、といったものです。
自分が試した限りでは二回タップしないとどうにもうまく動かなかったため、要望として投げます。
（いわゆる、イベントのタイミングで、「請求ボタンで確定」→「通貨切り替えポチ」ってしたら請求額のほうが固定されている関係で法定通貨のほうがずれており、現実では円やモナなど、ベースとなるほうで請求したいわけだからもう一回請求画面を開いて確定を押さないといけない、というトラブルが起こるな、と思いましたので。）

**Comment by MissMonacoin** [comment]
通貨切り替えたら非同期でレート取得が走るから直列にするのが面倒です

**Comment by kazu0617** [comment]
なるほどー(だから二回押さないとうまくいかなかったのか)

**Comment by kazu0617** [comment]
了解です。
