### ISSUE TITLE
Mac Safariでのバックグラウンドがおかしい

### ISSUE THREAD

**Issue by zinntikumugai** [MissMonacoin/monya#8]
![T](https://i.gyazo.com/f99afd459959f643a43918408d23aa54.png)
バックグラウンドが真っ黒になっています

**Comment by zinntikumugai** [comment]
ローディング時の画像も透過部分と思われる部分が黒く塗りつぶしされていました

**Comment by zinntikumugai** [comment]
![T](https://i.gyazo.com/5fcd9becd0b77f6dfb69c1cdf1bd3fbd.png)
可読性に難あり

**Comment by yuki-js** [comment]
お使いの端末のスペックを教えていただけますか？
- OS
- バージョン
- モデル、製造年
- プロセッサ
- メモリ
- グラフィックス
- ブラウザバージョン
- 他のブラウザでも同じかどうか
- 特殊な改造(rEFItなど)を行なっているかどうか
基本スペックは画面左上アップルボタン、このMacについてから確認できます。
スクリーンショットでも問題ありませんが、シリアル番号を隠すことをお忘れなく。

私の環境では正常に動作します
<img width="532" alt="2018-02-15 0 10 00" src="https://user-images.githubusercontent.com/20838151/36211451-9b7a1248-11e4-11e8-9c2a-b3ade550ef90.png">

**Comment by MissMonacoin** [comment]
お使いの端末のスペックを教えていただけますか？
- OS
- バージョン
- モデル、製造年
- プロセッサ
- メモリ
- グラフィックス
- ブラウザバージョン
- 他のブラウザでも同じかどうか
- 特殊な改造(rEFItなど)を行なっているかどうか
基本スペックは画面左上アップルボタン、このMacについてから確認できます。
スクリーンショットでも問題ありませんが、シリアル番号を隠すことをお忘れなく。

私の環境では正常に動作します
<img width="532" alt="2018-02-15 0 10 00" src="https://user-images.githubusercontent.com/20838151/36211451-9b7a1248-11e4-11e8-9c2a-b3ade550ef90.png">

**Comment by zinntikumugai** [comment]
VMwareを使用した仮想マシンなのでほぼサポート外として扱われるかもしれませんが念のため
CPU：Intel i5-2520m 4C うち2Core割当
RAM：8G うち 2G割当
OS：mac High Sierra
なお、VMwareの更新でイメージが破損し起動できなくなりました()
環境が主に影響していたかもしれません

**Comment by MissMonacoin** [comment]
それは仮想マシンの影響ですね。
