### ISSUE TITLE
iOS Safari doesn't support in QR-Scanner-Mode

### ISSUE THREAD

**Issue by kazu0617** [MissMonacoin/monya#9]
iOSでQRコードを読み込もうとした際
iOS11未満だとplayアイコンが表示され（勿論押しても反応はない）、
iOS11だと白背景になってしまい、本来行えるはずのQRコード確認のためのカメラ起動が行われない。

**Comment by yuki-js** [comment]
iOS実機を用意できないので現在調査不能です。
https://github.com/bitpay/cordova-plugin-qrscanner
このプラグインは最下層レイヤーにカメラが描画し、アプリ側は背景を透過させて見るのですが、body直下にvideo要素and/or canvas要素はありますか？

**Comment by kazu0617** [comment]
そもそも大前提としまして、iPhoneのSafari含めたブラウザではソースコード表示機能は用意されておらず、ブックマークレットを使用しての表示しかできません。
その上で、今回以下のような条件で確認しました。
- iPhone5 iOS10.3.2 / Safari
- ソースコード表示にSafariブックマークレットを使用)
- カメラモード時にブックマークレットを使用、[ソースコード表示](https://pastebin.com/xexzsUg7)
![iPhone 5](https://img1.picload.org/preview/dardwawa/img_0012.jpg)その時の画面表示は左の通りです。<br>
iPhone6Plus iOS11でも用意できますが、そちらも試しましょうか？

**Comment by MissMonacoin** [comment]
これはbitpayが無能すぎるのが問題ですね

**Comment by kazu0617** [comment]
bitpay/cordova-plugin-qrscannerのほうにて、もしかすると参考になるかもしれないものがありましたので参考までに掲載します。
https://github.com/bitpay/cordova-plugin-qrscanner/issues/95

**Comment by MissMonacoin** [comment]
実機でちょっとだけ調べてみましたが、
背景の透過はどう考えてもされている。
考えられることは、videoタグにautoplay, webkit-playsinlineがついていないことです。
これで解決するかどうかはわかりませんが。

**Comment by MissMonacoin** [comment]
つけてみました
お試しください。

**Comment by kazu0617** [comment]
先ほどテストしたところ、iOS11環境ですとカメラの許可->カメラの表示まで行えたのを確認しました。
iOS10までですと、ネイティブでのみの対応となっていますのでこれでクローズしますね。
対応ありがとうございますm(_ _)m
